"""001_initial_postgres_schema

Revision ID: b1815de543ea
Revises: baseline_001
Create Date: 2025-12-21 17:48:48.912813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1815de543ea'
down_revision: Union[str, Sequence[str], None] = 'baseline_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('hex_code_secondary', sa.String(length=7), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_code'), 'colors', ['code'], unique=True)
    op.create_index(op.f('ix_colors_id'), 'colors', ['id'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address_line1', sa.String(length=255), nullable=True),
    sa.Column('company_address_line2', sa.String(length=255), nullable=True),
    sa.Column('company_city', sa.String(length=100), nullable=True),
    sa.Column('company_state', sa.String(length=50), nullable=True),
    sa.Column('company_zip', sa.String(length=20), nullable=True),
    sa.Column('company_country', sa.String(length=100), nullable=True),
    sa.Column('company_phone', sa.String(length=30), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('logo_data', sa.LargeBinary(), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('logo_mime_type', sa.String(length=100), nullable=True),
    sa.Column('tax_enabled', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tax_name', sa.String(length=50), nullable=True),
    sa.Column('tax_registration_number', sa.String(length=100), nullable=True),
    sa.Column('default_quote_validity_days', sa.Integer(), nullable=False),
    sa.Column('quote_terms', sa.String(length=2000), nullable=True),
    sa.Column('quote_footer', sa.String(length=1000), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=True),
    sa.Column('invoice_terms', sa.String(length=2000), nullable=True),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=True),
    sa.Column('accounting_method', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_locations_id'), 'inventory_locations', ['id'], unique=False)
    op.create_table('item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_categories_code'), 'item_categories', ['code'], unique=True)
    op.create_index(op.f('ix_item_categories_id'), 'item_categories', ['id'], unique=False)
    op.create_table('material_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_material', sa.String(length=20), nullable=False),
    sa.Column('process_type', sa.String(length=20), nullable=False),
    sa.Column('density', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('volumetric_flow_limit', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nozzle_temp_min', sa.Integer(), nullable=True),
    sa.Column('nozzle_temp_max', sa.Integer(), nullable=True),
    sa.Column('bed_temp_min', sa.Integer(), nullable=True),
    sa.Column('bed_temp_max', sa.Integer(), nullable=True),
    sa.Column('requires_enclosure', sa.Boolean(), nullable=True),
    sa.Column('base_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strength_rating', sa.Integer(), nullable=True),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_types_base_material'), 'material_types', ['base_material'], unique=False)
    op.create_index(op.f('ix_material_types_code'), 'material_types', ['code'], unique=True)
    op.create_index(op.f('ix_material_types_id'), 'material_types', ['id'], unique=False)
    op.create_table('mrp_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('planning_horizon_days', sa.Integer(), nullable=False),
    sa.Column('orders_processed', sa.Integer(), nullable=True),
    sa.Column('components_analyzed', sa.Integer(), nullable=True),
    sa.Column('shortages_found', sa.Integer(), nullable=True),
    sa.Column('planned_orders_created', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mrp_runs_id'), 'mrp_runs', ['id'], unique=False)
    op.create_table('scrap_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrap_reasons_code'), 'scrap_reasons', ['code'], unique=True)
    op.create_index(op.f('ix_scrap_reasons_id'), 'scrap_reasons', ['id'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('uom_class', sa.String(length=20), nullable=False),
    sa.Column('base_unit_id', sa.Integer(), nullable=True),
    sa.Column('to_base_factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('to_base_factor > 0', name='check_to_base_factor_positive'),
    sa.ForeignKeyConstraint(['base_unit_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_of_measure_code'), 'units_of_measure', ['code'], unique=True)
    op.create_index(op.f('ix_units_of_measure_id'), 'units_of_measure', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('billing_address_line1', sa.String(length=255), nullable=True),
    sa.Column('billing_address_line2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=50), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=100), nullable=True),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=50), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_customer_number'), 'users', ['customer_number'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_table('work_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('center_type', sa.String(length=50), nullable=False),
    sa.Column('capacity_hours_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity_units_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('machine_rate_per_hour', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('labor_rate_per_hour', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('overhead_rate_per_hour', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_bottleneck', sa.Boolean(), nullable=False),
    sa.Column('scheduling_priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_centers_code'), 'work_centers', ['code'], unique=True)
    op.create_index(op.f('ix_work_centers_id'), 'work_centers', ['id'], unique=False)
    op.create_table('customer_traceability_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('traceability_level', sa.String(length=20), nullable=False),
    sa.Column('requires_coc', sa.Boolean(), nullable=True),
    sa.Column('requires_coa', sa.Boolean(), nullable=True),
    sa.Column('requires_first_article', sa.Boolean(), nullable=True),
    sa.Column('record_retention_days', sa.Integer(), nullable=True),
    sa.Column('custom_serial_prefix', sa.String(length=20), nullable=True),
    sa.Column('compliance_standards', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_traceability_profiles_id'), 'customer_traceability_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_customer_traceability_profiles_user_id'), 'customer_traceability_profiles', ['user_id'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('compatible_materials', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bed_size_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bed_size_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bed_size_z', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('bambu_serial', sa.String(length=100), nullable=True),
    sa.Column('bambu_access_code', sa.String(length=20), nullable=True),
    sa.Column('bambu_ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_code'), 'machines', ['code'], unique=True)
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_status'), 'machines', ['status'], unique=False)
    op.create_table('material_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('is_customer_visible', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_type_id', 'color_id', name='uq_material_color')
    )
    op.create_index(op.f('ix_material_colors_id'), 'material_colors', ['id'], unique=False)
    op.create_index('ix_material_colors_lookup', 'material_colors', ['material_type_id', 'color_id'], unique=False)
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('approval_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_requests_approval_token'), 'password_reset_requests', ['approval_token'], unique=True)
    op.create_index(op.f('ix_password_reset_requests_id'), 'password_reset_requests', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_status'), 'password_reset_requests', ['status'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_token'), 'password_reset_requests', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_requests_user_id'), 'password_reset_requests', ['user_id'], unique=False)
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('mqtt_topic', sa.String(length=255), nullable=True),
    sa.Column('connection_config', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_center_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_brand'), 'printers', ['brand'], unique=False)
    op.create_index(op.f('ix_printers_code'), 'printers', ['code'], unique=True)
    op.create_index(op.f('ix_printers_id'), 'printers', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('legacy_sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('procurement_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('material_type_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('cost_method', sa.String(length=20), nullable=True),
    sa.Column('standard_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('weight', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('weight_oz', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('length_in', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width_in', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height_in', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('preferred_vendor_id', sa.Integer(), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('gcode_file_path', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('sales_channel', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_raw_material', sa.Boolean(), nullable=True),
    sa.Column('has_bom', sa.Boolean(), nullable=True),
    sa.Column('track_lots', sa.Boolean(), nullable=True),
    sa.Column('track_serials', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('woocommerce_product_id', sa.BigInteger(), nullable=True),
    sa.Column('squarespace_product_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_legacy_sku'), 'products', ['legacy_sku'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('tracking_number', sa.String(length=200), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('bambu_device_id', sa.String(length=100), nullable=True),
    sa.Column('bambu_ip_address', sa.String(length=50), nullable=True),
    sa.Column('capacity_hours_per_day', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_code'), 'resources', ['code'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('boms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('revision', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('assembly_time_minutes', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boms_id'), 'boms', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('on_hand_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=10, scale=2), sa.Computed('on_hand_quantity - allocated_quantity', ), nullable=True),
    sa.Column('last_counted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_table('material_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reorder_point_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('last_purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_vendor', sa.String(length=100), nullable=True),
    sa.Column('vendor_sku', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['material_type_id'], ['material_types.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_type_id', 'color_id', name='uq_material_inventory')
    )
    op.create_index(op.f('ix_material_inventory_color_id'), 'material_inventory', ['color_id'], unique=False)
    op.create_index(op.f('ix_material_inventory_id'), 'material_inventory', ['id'], unique=False)
    op.create_index('ix_material_inventory_lookup', 'material_inventory', ['material_type_id', 'color_id'], unique=False)
    op.create_index(op.f('ix_material_inventory_material_type_id'), 'material_inventory', ['material_type_id'], unique=False)
    op.create_index(op.f('ix_material_inventory_product_id'), 'material_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_material_inventory_sku'), 'material_inventory', ['sku'], unique=True)
    op.create_index('ix_material_inventory_stock', 'material_inventory', ['in_stock', 'active'], unique=False)
    op.create_table('material_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_lot_number', sa.String(length=100), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_scrapped', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quantity_adjusted', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('certificate_of_analysis', sa.Text(), nullable=True),
    sa.Column('coa_file_path', sa.String(length=500), nullable=True),
    sa.Column('inspection_status', sa.String(length=30), nullable=True),
    sa.Column('manufactured_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lot_expiration', 'material_lots', ['expiration_date'], unique=False)
    op.create_index('ix_lot_product_status', 'material_lots', ['product_id', 'status'], unique=False)
    op.create_index('ix_lot_received_date', 'material_lots', ['received_date'], unique=False)
    op.create_index(op.f('ix_material_lots_expiration_date'), 'material_lots', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_material_lots_id'), 'material_lots', ['id'], unique=False)
    op.create_index(op.f('ix_material_lots_lot_number'), 'material_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_material_lots_product_id'), 'material_lots', ['product_id'], unique=False)
    op.create_index(op.f('ix_material_lots_status'), 'material_lots', ['status'], unique=False)
    op.create_index(op.f('ix_material_lots_vendor_id'), 'material_lots', ['vendor_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('finish', sa.String(length=50), nullable=True),
    sa.Column('gcode_file_path', sa.String(length=500), nullable=True),
    sa.Column('material_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('print_time_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('image_data', sa.LargeBinary(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('dimensions_x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions_y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions_z', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approval_method', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_eligible', sa.Boolean(), nullable=False),
    sa.Column('requires_review_reason', sa.String(length=255), nullable=True),
    sa.Column('rush_level', sa.String(length=20), nullable=True),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('customer_notes', sa.String(length=1000), nullable=True),
    sa.Column('admin_notes', sa.String(length=1000), nullable=True),
    sa.Column('internal_notes', sa.String(length=1000), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('shipping_name', sa.String(length=200), nullable=True),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=50), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('shipping_phone', sa.String(length=30), nullable=True),
    sa.Column('shipping_rate_id', sa.String(length=100), nullable=True),
    sa.Column('shipping_carrier', sa.String(length=50), nullable=True),
    sa.Column('shipping_service', sa.String(length=100), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_customer_id'), 'quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_product_id'), 'quotes', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index(op.f('ix_quotes_user_id'), 'quotes', ['user_id'], unique=False)
    op.create_table('routings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_setup_time_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_run_time_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routings_code'), 'routings', ['code'], unique=False)
    op.create_index(op.f('ix_routings_id'), 'routings', ['id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('consume_stage', sa.String(length=20), nullable=False),
    sa.Column('is_cost_only', sa.Boolean(), nullable=False),
    sa.Column('scrap_factor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_lines_id'), 'bom_lines', ['id'], unique=False)
    op.create_table('quote_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.String(length=1000), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('triangle_count', sa.Integer(), nullable=True),
    sa.Column('bambu_file_id', sa.String(length=100), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_quote_files_file_hash'), 'quote_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_quote_files_id'), 'quote_files', ['id'], unique=False)
    op.create_index(op.f('ix_quote_files_quote_id'), 'quote_files', ['quote_id'], unique=False)
    op.create_table('quote_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=30), nullable=True),
    sa.Column('color_name', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('material_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_materials_id'), 'quote_materials', ['id'], unique=False)
    op.create_index(op.f('ix_quote_materials_quote_id'), 'quote_materials', ['quote_id'], unique=False)
    op.create_table('routing_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_code', sa.String(length=50), nullable=True),
    sa.Column('operation_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setup_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('run_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wait_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('move_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('runtime_source', sa.String(length=50), nullable=False),
    sa.Column('slicer_file_path', sa.String(length=500), nullable=True),
    sa.Column('units_per_cycle', sa.Integer(), nullable=False),
    sa.Column('scrap_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('labor_rate_override', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('machine_rate_override', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('predecessor_operation_id', sa.Integer(), nullable=True),
    sa.Column('can_overlap', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_operation_id'], ['routing_operations.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_operations_id'), 'routing_operations', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_order_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('finish', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=False),
    sa.Column('rush_level', sa.String(length=20), nullable=False),
    sa.Column('estimated_completion_date', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(), nullable=True),
    sa.Column('shipping_address_line1', sa.String(length=255), nullable=True),
    sa.Column('shipping_address_line2', sa.String(length=255), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=50), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('production_notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('mrp_status', sa.String(length=50), nullable=True),
    sa.Column('mrp_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mrp_run_id'], ['mrp_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_orders_created_at'), 'sales_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_orders_fulfillment_status'), 'sales_orders', ['fulfillment_status'], unique=False)
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_index(op.f('ix_sales_orders_mrp_run_id'), 'sales_orders', ['mrp_run_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_mrp_status'), 'sales_orders', ['mrp_status'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_number'), 'sales_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_sales_orders_order_type'), 'sales_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_sales_orders_payment_status'), 'sales_orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_sales_orders_product_id'), 'sales_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_quote_id'), 'sales_orders', ['quote_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_source'), 'sales_orders', ['source'], unique=False)
    op.create_index(op.f('ix_sales_orders_source_order_id'), 'sales_orders', ['source_order_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_status'), 'sales_orders', ['status'], unique=False)
    op.create_index(op.f('ix_sales_orders_user_id'), 'sales_orders', ['user_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('metadata_key', sa.String(length=100), nullable=True),
    sa.Column('metadata_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_created_at'), 'order_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_events_event_type'), 'order_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_events_id'), 'order_events', ['id'], unique=False)
    op.create_index(op.f('ix_order_events_sales_order_id'), 'order_events', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_order_events_user_id'), 'order_events', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('check_number', sa.String(length=50), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.create_index(op.f('ix_payments_recorded_by_id'), 'payments', ['recorded_by_id'], unique=False)
    op.create_index(op.f('ix_payments_sales_order_id'), 'payments', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('sales_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipped_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_lines_id'), 'sales_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_sales_order_lines_product_id'), 'sales_order_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_order_lines_sales_order_id'), 'sales_order_lines', ['sales_order_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=True),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.Column('split_sequence', sa.Integer(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_completed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_scrapped', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('qc_status', sa.String(length=50), nullable=False),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('qc_inspected_by', sa.String(length=100), nullable=True),
    sa.Column('qc_inspected_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_time_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_material_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_labor_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_material_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_labor_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_total_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scrap_reason', sa.String(length=100), nullable=True),
    sa.Column('scrapped_at', sa.DateTime(), nullable=True),
    sa.Column('remake_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['parent_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['remake_of_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['routings.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_code'), 'production_orders', ['code'], unique=True)
    op.create_index(op.f('ix_production_orders_due_date'), 'production_orders', ['due_date'], unique=False)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_parent_order_id'), 'production_orders', ['parent_order_id'], unique=False)
    op.create_index(op.f('ix_production_orders_status'), 'production_orders', ['status'], unique=False)
    op.create_table('planned_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('source_demand_type', sa.String(length=50), nullable=True),
    sa.Column('source_demand_id', sa.Integer(), nullable=True),
    sa.Column('mrp_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_to_po_id', sa.Integer(), nullable=True),
    sa.Column('converted_to_mo_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('firmed_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_mo_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['converted_to_po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['mrp_run_id'], ['mrp_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_orders_id'), 'planned_orders', ['id'], unique=False)
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('gcode_file', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_time_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_material_grams', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_material_grams', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('variance_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_jobs_id'), 'print_jobs', ['id'], unique=False)
    op.create_table('production_order_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('routing_operation_id', sa.Integer(), nullable=True),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_code', sa.String(length=50), nullable=True),
    sa.Column('operation_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quantity_completed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('quantity_scrapped', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('planned_setup_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('planned_run_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_setup_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_run_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('bambu_task_id', sa.String(length=100), nullable=True),
    sa.Column('bambu_plate_index', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['routing_operation_id'], ['routing_operations.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_order_operations_id'), 'production_order_operations', ['id'], unique=False)
    op.create_index(op.f('ix_production_order_operations_status'), 'production_order_operations', ['status'], unique=False)
    op.create_table('serial_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('qc_passed', sa.Boolean(), nullable=False),
    sa.Column('qc_date', sa.DateTime(), nullable=True),
    sa.Column('qc_notes', sa.Text(), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_line_id', sa.Integer(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('manufactured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['sales_order_line_id'], ['sales_order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_serial_manufactured_date', 'serial_numbers', ['manufactured_at'], unique=False)
    op.create_index(op.f('ix_serial_numbers_id'), 'serial_numbers', ['id'], unique=False)
    op.create_index(op.f('ix_serial_numbers_product_id'), 'serial_numbers', ['product_id'], unique=False)
    op.create_index(op.f('ix_serial_numbers_production_order_id'), 'serial_numbers', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_serial_numbers_sales_order_id'), 'serial_numbers', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_serial_numbers_serial_number'), 'serial_numbers', ['serial_number'], unique=True)
    op.create_index(op.f('ix_serial_numbers_status'), 'serial_numbers', ['status'], unique=False)
    op.create_index('ix_serial_product_status', 'serial_numbers', ['product_id', 'status'], unique=False)
    op.create_table('production_lot_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('material_lot_id', sa.Integer(), nullable=False),
    sa.Column('serial_number_id', sa.Integer(), nullable=True),
    sa.Column('bom_line_id', sa.Integer(), nullable=True),
    sa.Column('quantity_consumed', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bom_line_id'], ['bom_lines.id'], ),
    sa.ForeignKeyConstraint(['material_lot_id'], ['material_lots.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['serial_number_id'], ['serial_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumption_lot_production', 'production_lot_consumptions', ['material_lot_id', 'production_order_id'], unique=False)
    op.create_index(op.f('ix_production_lot_consumptions_id'), 'production_lot_consumptions', ['id'], unique=False)
    op.create_index(op.f('ix_production_lot_consumptions_material_lot_id'), 'production_lot_consumptions', ['material_lot_id'], unique=False)
    op.create_index(op.f('ix_production_lot_consumptions_production_order_id'), 'production_lot_consumptions', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_production_lot_consumptions_serial_number_id'), 'production_lot_consumptions', ['serial_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_lot_consumptions_serial_number_id'), table_name='production_lot_consumptions')
    op.drop_index(op.f('ix_production_lot_consumptions_production_order_id'), table_name='production_lot_consumptions')
    op.drop_index(op.f('ix_production_lot_consumptions_material_lot_id'), table_name='production_lot_consumptions')
    op.drop_index(op.f('ix_production_lot_consumptions_id'), table_name='production_lot_consumptions')
    op.drop_index('ix_consumption_lot_production', table_name='production_lot_consumptions')
    op.drop_table('production_lot_consumptions')
    op.drop_index('ix_serial_product_status', table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_status'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_serial_number'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_sales_order_id'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_production_order_id'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_product_id'), table_name='serial_numbers')
    op.drop_index(op.f('ix_serial_numbers_id'), table_name='serial_numbers')
    op.drop_index('ix_serial_manufactured_date', table_name='serial_numbers')
    op.drop_table('serial_numbers')
    op.drop_index(op.f('ix_production_order_operations_status'), table_name='production_order_operations')
    op.drop_index(op.f('ix_production_order_operations_id'), table_name='production_order_operations')
    op.drop_table('production_order_operations')
    op.drop_index(op.f('ix_print_jobs_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_planned_orders_id'), table_name='planned_orders')
    op.drop_table('planned_orders')
    op.drop_index(op.f('ix_production_orders_status'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_parent_order_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_due_date'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_code'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_sales_order_lines_sales_order_id'), table_name='sales_order_lines')
    op.drop_index(op.f('ix_sales_order_lines_product_id'), table_name='sales_order_lines')
    op.drop_index(op.f('ix_sales_order_lines_id'), table_name='sales_order_lines')
    op.drop_table('sales_order_lines')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_sales_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_recorded_by_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_events_user_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_sales_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_event_type'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_created_at'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index(op.f('ix_sales_orders_user_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_source_order_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_source'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_quote_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_product_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_payment_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_type'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_order_number'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_mrp_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_mrp_run_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_fulfillment_status'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_created_at'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_routing_operations_id'), table_name='routing_operations')
    op.drop_table('routing_operations')
    op.drop_index(op.f('ix_quote_materials_quote_id'), table_name='quote_materials')
    op.drop_index(op.f('ix_quote_materials_id'), table_name='quote_materials')
    op.drop_table('quote_materials')
    op.drop_index(op.f('ix_quote_files_quote_id'), table_name='quote_files')
    op.drop_index(op.f('ix_quote_files_id'), table_name='quote_files')
    op.drop_index(op.f('ix_quote_files_file_hash'), table_name='quote_files')
    op.drop_table('quote_files')
    op.drop_index(op.f('ix_bom_lines_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_routings_id'), table_name='routings')
    op.drop_index(op.f('ix_routings_code'), table_name='routings')
    op.drop_table('routings')
    op.drop_index(op.f('ix_quotes_user_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_product_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_customer_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_material_lots_vendor_id'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_status'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_product_id'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_lot_number'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_id'), table_name='material_lots')
    op.drop_index(op.f('ix_material_lots_expiration_date'), table_name='material_lots')
    op.drop_index('ix_lot_received_date', table_name='material_lots')
    op.drop_index('ix_lot_product_status', table_name='material_lots')
    op.drop_index('ix_lot_expiration', table_name='material_lots')
    op.drop_table('material_lots')
    op.drop_index('ix_material_inventory_stock', table_name='material_inventory')
    op.drop_index(op.f('ix_material_inventory_sku'), table_name='material_inventory')
    op.drop_index(op.f('ix_material_inventory_product_id'), table_name='material_inventory')
    op.drop_index(op.f('ix_material_inventory_material_type_id'), table_name='material_inventory')
    op.drop_index('ix_material_inventory_lookup', table_name='material_inventory')
    op.drop_index(op.f('ix_material_inventory_id'), table_name='material_inventory')
    op.drop_index(op.f('ix_material_inventory_color_id'), table_name='material_inventory')
    op.drop_table('material_inventory')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_boms_id'), table_name='boms')
    op.drop_table('boms')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_code'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_legacy_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_printers_id'), table_name='printers')
    op.drop_index(op.f('ix_printers_code'), table_name='printers')
    op.drop_index(op.f('ix_printers_brand'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_password_reset_requests_user_id'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_token'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_status'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_id'), table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_approval_token'), table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    op.drop_index('ix_material_colors_lookup', table_name='material_colors')
    op.drop_index(op.f('ix_material_colors_id'), table_name='material_colors')
    op.drop_table('material_colors')
    op.drop_index(op.f('ix_machines_status'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_code'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_customer_traceability_profiles_user_id'), table_name='customer_traceability_profiles')
    op.drop_index(op.f('ix_customer_traceability_profiles_id'), table_name='customer_traceability_profiles')
    op.drop_table('customer_traceability_profiles')
    op.drop_index(op.f('ix_work_centers_id'), table_name='work_centers')
    op.drop_index(op.f('ix_work_centers_code'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_customer_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_of_measure_id'), table_name='units_of_measure')
    op.drop_index(op.f('ix_units_of_measure_code'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_scrap_reasons_id'), table_name='scrap_reasons')
    op.drop_index(op.f('ix_scrap_reasons_code'), table_name='scrap_reasons')
    op.drop_table('scrap_reasons')
    op.drop_index(op.f('ix_mrp_runs_id'), table_name='mrp_runs')
    op.drop_table('mrp_runs')
    op.drop_index(op.f('ix_material_types_id'), table_name='material_types')
    op.drop_index(op.f('ix_material_types_code'), table_name='material_types')
    op.drop_index(op.f('ix_material_types_base_material'), table_name='material_types')
    op.drop_table('material_types')
    op.drop_index(op.f('ix_item_categories_id'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_code'), table_name='item_categories')
    op.drop_table('item_categories')
    op.drop_index(op.f('ix_inventory_locations_id'), table_name='inventory_locations')
    op.drop_table('inventory_locations')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_colors_id'), table_name='colors')
    op.drop_index(op.f('ix_colors_code'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###
